[build]
    command = "npm run build"
    publish = "dist"

[functions]
    directory = 'functions'
    node_bundler = 'esbuild'
    external_node_modules = ['mongodb']

[dev]
    command = "npm start"
    publish = "src"